name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  node_env:  # id of input
    description: 'The node env'
    required: true
    default: 'development'
outputs:
  time: # id of output
    description: 'The time of completion'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.node_env }}
